default:
  image: node:18.14

stages:
  - setup
  - build

install:
  stage: setup
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull-push
  script:
    - npm ci
  only:
    - main
    - merge_requests

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - merge_requests
