name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:18.18
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
        lookup-only: true
    - run: npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: node:18.18
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: "node_modules-${{ hashFiles('package-lock.json') }}"
    - run: npm run build:ci
